// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvunvmdxbmjooulunphg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2dW52bWR4Ym1qb291bHVucGhnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NDYwNjQsImV4cCI6MjA3NDAyMjA2NH0.EShdpn7r025PqgwIdjj8AdbJuD4F0HXhZ2Uh5WLrGDI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});